### ISSUE TITLE
BCM 43430 wifi firmware confusion

### ISSUE THREAD

**Issue by martingkelly** [armbian/firmware#1]
Hi,

I've been testing the wifi on my nano pi neo air (using my own distro rather than Armbian's), and I noticed that everything works if I use the firmware here, but it does not work if I use the official firmware from upstream linux-firmware. Specifically, this firmware works:
https://github.com/armbian/firmware/commit/3aa265d38307115a8be673aeaf16ec36439b6d06#diff-d3a21be2a9742eb1a16ab73c5dc6b4bf

and this firmware does not work:
https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/tree/brcm/brcmfmac43430-sdio.bin

Although it loads, it then spews these errors repeatedly:
```
[   13.614231] sunxi-mmc 1c10000.mmc: data error, sending stop command
[   13.622584] sunxi-mmc 1c10000.mmc: data error, sending stop command
[   13.631050] sunxi-mmc 1c10000.mmc: data error, sending stop command
[   13.637422] brcmfmac: brcmf_sdiod_regrw_helper: failed to read data F1@0x0a020, err: -110
[   13.645659] brcmfmac: brcmf_sdio_dpc: failed backplane access over SDIO, halting operation
```

I noticed this commit from @zador-blood-stained :
https://github.com/armbian/firmware/commit/3aa265d38307115a8be673aeaf16ec36439b6d06

In which the working firmware was added, but the commit didn't describe the full situation.

I should add: the working armbian firmware says this on boot:
```
[    1.294889] brcmfmac: brcmf_fw_map_chip_to_name: using brcm/brcmfmac43430-sdio.bin for chip 0x00a9a6(43430) rev 0x000001
[    1.463020] brcmfmac: brcmf_c_preinit_dcmds: Firmware version = wl0: Mar 30 2016 11:30:56 version 7.45.77.h8.4 FWID 01-ee8a6268
```

the official firmware says:
```
[    1.213839] brcmfmac: brcmf_fw_map_chip_to_name: using brcm/brcmfmac43430-sdio.bin for chip 0x00a9a6(43430) rev 0x000001
[    2.542548] brcmfmac: brcmf_c_preinit_dcmds: Firmware version = wl0: Aug  7 2017 00:46:29 version 7.45.41.46 (r666254 CY) FWID 01-f8a78378
```

So the official is supposedly newer and yet does not work.

Also, I'm using this unmerged DT patch to make wifi work:
https://patchwork.kernel.org/patch/9642071/

Could someone clarify why armbian's firmware works and the official firmware does not?

**Comment by zador-blood-stained** [comment]
> Could someone clarify why armbian's firmware works and the official firmware does not?

I don't remember exactly where I've found this firmware, most likely I just searched for `brcmfmac43430-sdio.bin` files, tested them and added the one that worked for me. You could probably do the same search and once you find a file with the same md5 you'll know where "my" copy came from.

**Comment by martingkelly** [comment]
Thanks; I did more investigation and found out both binary firmware versions work fine, but I was using the wrong txt file. When I use the txt file frim this repository, then everything works both on the version here and in the upstream linux-firmware.
